import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:covibattle/models/cityapi.dart';

Future<List<Autogenerated>> getAllPosts() async {
  final response = await http.get("https://api.covid19india.org/v2/state_district_wise.json");
  final allPostsFromJson=jsonDecode(response.body);
  return allPostsFromJson;
}